import createClient from 'openapi-fetch';
import type { Logger } from 'pino';

import type { paths } from '../model/tempworks'; // generated by openapi-typescript

const DEFAULT_API_TIMEOUT_MS = 60000; // 1 min in ms

export type TempWorksAuth = {
  type: 'Basic';
  accountSID: string;
  authToken: string;
};

const fetchFactory = (opts: { timeoutMs?: number | undefined; logger: Logger }): typeof fetch =>
  async function fetchWithTimeout(...[input, init = {}]: Parameters<typeof fetch>) {
    const controller = new AbortController();
    const id = setTimeout(() => controller.abort(), opts.timeoutMs ?? DEFAULT_API_TIMEOUT_MS);

    const request = new Request(input, {
      ...init,
      signal: controller.signal,
    });

    const loggingHeaders: Record<string, string> = {};
    request.headers.forEach(
      (v, k) =>
        (loggingHeaders[k] = ['authorization', 'x-tw-token'].includes(k.toLowerCase()) ? '***' + v.slice(-3) : v),
    );

    const requestURL = new URL(request.url);
    const logger = opts.logger.child(
      {
        request: {
          method: request.method,
          origin: requestURL.origin,
          pathname: requestURL.pathname,
          headers: loggingHeaders,
          query: requestURL.search,
          body: await request.clone().text(),
        },
      },
      { msgPrefix: `${request.method} ${request.url} ` },
    );

    const response = await fetch(request);
    clearTimeout(id);

    const responseHeaders: Record<string, string> = {};
    for (const [k, v] of response.headers.entries()) {
      responseHeaders[k] = v;
    }
    if (!response.ok) {
      logger.error(
        {
          response: {
            status: response.status,
            body: await response.clone().text(),
            headers: responseHeaders,
          },
        },
        'Failed rest api request',
      );
    } else
      logger.info(
        {
          response: {
            status: response.status,
            body: await response.clone().text(),
            headers: responseHeaders,
          },
        },
        `Rest api response`,
      );

    return response;
  };

export const apiFetch = (opts: {
  timeoutMs?: number;
  logger: Logger;
  baseUrl?: string;
  auth: TempWorksAuth | (() => Promise<TempWorksAuth>);
}) => {
  const { baseUrl = 'https://api.ontempworks.com', timeoutMs, logger } = opts;

  const client = createClient<paths>({ baseUrl, fetch: fetchFactory({ timeoutMs, logger }) });
  client.use({
    async onRequest(request) {
      const auth = typeof opts.auth === 'function' ? await opts.auth() : opts.auth;

      let authHeader: string;
      switch (auth.type) {
        case 'Basic':
          authHeader = 'Basic ' + Buffer.from(`${auth.accountSID}:${auth.authToken}`).toString('base64');
          break;

        default: {
          logger.error({ ...auth, authToken: '***' + (auth.authToken ?? '').slice(-3) }, 'provided auth type invalid');
          throw new Error('provided auth type invalid');
        }
      }

      request.headers.set('Authorization', authHeader);
      return request;
    },
  });
  return client;
};
